# Generated by Django 4.2.30 on 2026-07-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_testimonial_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(default='About Fit & Fine Forever', max_length=200)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('founder_name', models.CharField(default='Nutritionist Debasmita', max_length=100)),
                ('founder_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
        ),
    ]
