# Generated by Django 4.2.30 on 2026-08-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_number',
            field=models.CharField(default='919007104448', help_text='WhatsApp number in international format without + or spaces, e.g. 919007104448', max_length=20),
        ),
    ]
